### ISSUE TITLE
Failing to load SVG on host

### ISSUE THREAD

**Issue by JustinTBrown** [stevie-mayhew/silverstripe-svg#10]
Hi not to sure why this is happening, but on my host svg loading is failing. I'm getting the following error:
```
[Warning] DOMDocument::load(): I/O warning : failed to load external entity "/var/www/releases/1495733380/themes/market/images/Events.svg"
```
The file is definitely there and the path is correct. This is working perfectly on my local installation, and I am not able to determine why it would be different on my host.

The only clue I have as to what is going has to do with my templates. Currently I'm using `$SVG(param)` within an Include where `param` is a template variable being passed in through the Include. Here is a simplified example:

My page layout includes a content block:
```
<% include ContentBlock FirstCategory=$FirstCategory, Title=$Title %>
```
Which passes variables to be used within the Include itself:
```html
<div class="content-block">
    <div class="icon">
      $SVG($FirstCategory)
    </div>
    <h2 class="article-title">$Title</h2>
</div>
```
Though the path generates correctly as shown above in the error message, the file loading still fails. Interstingly if I replace the `$FirstCategory` template variable above with a constant, `events`, so that we have `$SVG(events)` now, everything works as expected.

Can't figure out why $SVG() won't accept a value from a template variable.

**Comment by JustinTBrown** [comment]
Wow, literally just realized what was happening.

I need to convert the string from `$FirstCategory` to lowercase to match the filename `events.svg`. Instead the SVG module is trying to load `Events.svg`. I'm not sure why this didn't fail on my local setup, but at least I caught it!

**Comment by stevie-mayhew** [comment]
Glad you tracked it down!
