### ISSUE TITLE
custom base path get overriden by config base_path

### ISSUE THREAD

**Issue by priscillay-toast** [stevie-mayhew/silverstripe-svg#22]
Custom base path stopped working with the latest release 2.4, subsites icons are missing as icons may not be in the same base_path set in yml.

For example: 
`$SVG('search').customBasePath('themes/{$subsiteTheme}/dist/images/svg/')` will not render if base_path is set `"themes/{$mainsiteTheme}/dist/images/svg/"`

**Comment by stevie-mayhew** [comment]
@wilr want to have a crack at fixing that up? :D

**Comment by wilr** [comment]
Sorry for that! Resolved and added a unit test now

**Comment by stevie-mayhew** [comment]
Thanks mate

**Comment by stevie-mayhew** [comment]
@priscillay-toast hope that works!
