### ISSUE TITLE
Correct template syntax?

### ISSUE THREAD

**Issue by JustinTBrown** [stevie-mayhew/silverstripe-svg#9]
Sorry for the obtuse question, but what is the correct template syntax to be using? The documentation calls for `{ $SVG('name') }` but as far as I know template variables in SS (if this is, indeed, intended to be called as a template variable) have a syntax of `$Foo` or `$Foo(param)` without curly braces. What am I missing? :)

**Comment by stevie-mayhew** [comment]
Hey @JustinTBrown - you can use either if it work! We just prefer to use the `'string'` so its obvious in templates that it is a string

**Comment by JustinTBrown** [comment]
@stevie-mayhew Makes sense thanks!
